<?php
return [
    'clara' => [
        'id' => 'clara',
        'name' => 'Clara J. M. Psi., Psikolog',
        'image' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=600&h=800',
        'specialties' => ['Burnout', 'Anxiety', 'Relationships'],
        'badges' => 'Licensed Clinical Psychologist',
        'bio1' => "Hello, I'm Clara. Over the past several years, I've dedicated my practice to helping individuals navigate the overwhelming pressures of modern life. Whether you're feeling stuck, experiencing severe burnout, or struggling to communicate effectively in your relationships, I'm here to listen.",
        'bio2' => "My approach to therapy is deeply rooted in Cognitive Behavioral Therapy (CBT) and Mindfulness. I believe that true healing begins in a space where you feel entirely safe, heard, and unjudged.",
        'experience' => '5+ Years',
        'languages' => 'ID, EN',
        'price' => '249.000',
        
        // Custom Directory UI properties
        'rating' => '4.9',
        'sessions' => '50+',
        'original_price' => '349.000',
        'discount' => '-28%',
        'schedules' => ['Today, 19:00', 'Today, 20:30'],
        'swimlanes' => ['today', 'highly_recommended']
    ],
    'budi' => [
        'id' => 'budi',
        'name' => 'Budi S. M. Psi., Psikolog',
        'image' => 'https://images.unsplash.com/photo-1556157382-97eda2d62296?auto=format&fit=crop&q=80&w=600&h=800',
        'specialties' => ['Depression', 'Stress', 'Anxiety'],
        'badges' => 'Licensed Clinical Psychologist',
        'bio1' => "Hi, I'm Budi. I specialize in helping clients manage acute stress and depressive episodes. I provide a calm, analytical, and structured approach to emotional healing.",
        'bio2' => "We will work together using evidence-based practices to map out your emotional triggers and build a sustainable routine for your mental well-being.",
        'experience' => '8+ Years',
        'languages' => 'ID',
        'price' => '300.000',
        
        'rating' => '5.0',
        'sessions' => '120+',
        'original_price' => '400.000',
        'discount' => '-25%',
        'schedules' => ['Today, 18:00', 'Tomorrow, 10:00'],
        'swimlanes' => ['today', 'evening']
    ],
    'nina' => [
        'id' => 'nina',
        'name' => 'Nina W. M. Psi., Psikolog',
        'image' => 'https://images.unsplash.com/photo-1594824436951-7f12bc416f49?auto=format&fit=crop&q=80&w=600&h=800',
        'specialties' => ['Trauma', 'Anxiety', 'Family Issues'],
        'badges' => 'Licensed Clinical Psychologist',
        'bio1' => "Welcome. I am Nina, a trauma-informed psychologist. My sessions are designed to be a completely safe haven for you to unravel complex emotions and past experiences without any judgment.",
        'bio2' => "Through gentle narrative therapy and ACT (Acceptance and Commitment Therapy), I will guide you toward inner peace and emotional regulation.",
        'experience' => '6+ Years',
        'languages' => 'ID, EN',
        'price' => '300.000',
        
        'rating' => '4.8',
        'sessions' => '90+',
        'original_price' => null,
        'discount' => null,
        'schedules' => ['Today, 20:00'],
        'swimlanes' => ['today', 'evening']
    ],
    'rizky' => [
        'id' => 'rizky',
        'name' => 'Rizky A. M. Psi., Psikolog',
        'image' => 'https://images.unsplash.com/photo-1537368910025-702804a9af4f?auto=format&fit=crop&q=80&w=600&h=800',
        'specialties' => ['Career Transition', 'Burnout', 'Stress'],
        'badges' => 'Licensed Clinical Psychologist',
        'bio1' => "Hello, I am Rizky. If you are facing a massive quarter-life crisis or feeling entirely burnt out by your professional career, you are not alone.",
        'bio2' => "I focus heavily on goal-oriented counseling. We will identify your core values and realign your life choices so you can wake up feeling energized and purposeful.",
        'experience' => '4+ Years',
        'languages' => 'ID, EN',
        'price' => '280.000',
        
        'rating' => '4.9',
        'sessions' => '45+',
        'original_price' => '350.000',
        'discount' => '-20%',
        'schedules' => ['Sat, 10:00', 'Sun, 14:00'],
        'swimlanes' => ['evening', 'highly_recommended']
    ],
    'sarah' => [
        'id' => 'sarah',
        'name' => 'Dr. Sarah L. Psikolog',
        'image' => 'https://images.unsplash.com/photo-1588516903720-8ceb67f9ef84?auto=format&fit=crop&q=80&w=600&h=800',
        'specialties' => ['Relationships', 'Intimacy'],
        'badges' => 'Senior Counseling Expert',
        'bio1' => "Hello, I'm Dr. Sarah. I specialize in couples therapy and severe conflict resolution. Relationships are complex, and it is entirely normal to need a neutral mediator.",
        'bio2' => "In my room, both partners will be heard equally. I utilize emotionally focused therapy (EFT) to rebuild broken trust and foster deep, lasting intimacy.",
        'experience' => '12+ Years',
        'languages' => 'ID, EN, NL',
        'price' => '400.000',
        
        'rating' => '5.0',
        'sessions' => '300+',
        'original_price' => null,
        'discount' => null,
        'schedules' => ['Fri, 18:30', 'Sat, 09:00'],
        'swimlanes' => ['evening', 'highly_recommended']
    ],
    'anton' => [
        'id' => 'anton',
        'name' => 'Dr. Anton W. Psikolog',
        'image' => 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=600&h=800',
        'specialties' => ['Anger Management', 'Stress'],
        'badges' => 'Behavioral Specialist',
        'bio1' => "Hello, I'm Dr. Anton. Uncontrolled anger is fundamentally a highly reactive stress response covering deeper unaddressed insecurities. My sessions aim to decode these sudden outbursts safely.",
        'bio2' => "We will utilize Dialectical Behavior Therapy (DBT) frameworks to build exceptional emotional tolerance. My goal is giving you complete autonomy over your reactions.",
        'experience' => '10+ Years',
        'languages' => 'ID, EN',
        'price' => '320.000',
        'rating' => '4.8',
        'sessions' => '200+',
        'original_price' => '400.000',
        'discount' => '-20%',
        'schedules' => ['Today, 14:00', 'Thu, 09:00'],
        'swimlanes' => ['today', 'highly_recommended']
    ],
    'maya' => [
        'id' => 'maya',
        'name' => 'Maya S. M. Psi., Psikolog',
        'image' => 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=600&h=800',
        'specialties' => ['Eating Disorders', 'Anxiety', 'Self-Esteem'],
        'badges' => 'Licensed Clinical Psychologist',
        'bio1' => "Hi, I am Maya. Recovering from deeply ingrained body image issues and eating disorders requires an incredibly empathetic, non-triggering environment. I am here to provide exactly that.",
        'bio2' => "Using body-neutrality practices and structured CBT, we will slowly dismantle destructive eating patterns, helping you rediscover joy and safety in your physical self.",
        'experience' => '7+ Years',
        'languages' => 'ID',
        'price' => '280.000',
        'rating' => '4.9',
        'sessions' => '150+',
        'original_price' => null,
        'discount' => null,
        'schedules' => ['Tomorrow, 16:00', 'Sat, 11:00'],
        'swimlanes' => ['evening']
    ],
    'dimas' => [
        'id' => 'dimas',
        'name' => 'Dimas R. M. Psi., Psikolog',
        'image' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=600&h=800',
        'specialties' => ['Depression', 'LGBTQ+ Support'],
        'badges' => 'Inclusive Counseling Expert',
        'bio1' => "Welcome. I am Dimas. Navigating heavy depressive episodes, especially when compounded by identity and societal struggles, is exhausting. In my room, you can put your heavy armor down.",
        'bio2' => "I employ a highly affirmative, client-centered approach. Together, we will gently process systemic stress and build personalized frameworks for finding your authentic joy.",
        'experience' => '5+ Years',
        'languages' => 'ID, EN',
        'price' => '250.000',
        'rating' => '5.0',
        'sessions' => '60+',
        'original_price' => '300.000',
        'discount' => '-15%',
        'schedules' => ['Today, 21:00', 'Wed, 19:30'],
        'swimlanes' => ['today', 'evening']
    ],
    'siti' => [
        'id' => 'siti',
        'name' => 'Dr. Siti F. Psikolog',
        'image' => 'https://images.unsplash.com/photo-1531123897727-8f129e1b4cac?auto=format&fit=crop&q=80&w=600&h=800',
        'specialties' => ['Parenting', 'Trauma'],
        'badges' => 'Family Therapy Specialist',
        'bio1' => "Hello, I am Dr. Siti. The journey of parenting can inadvertently unearth our own unresolved childhood traumas. I provide a secure space to process both the struggles of raising children and healing your inner self.",
        'bio2' => "I integrate EMDR therapy with modern attachment-theory parenting paradigms, giving you the tools to break generational cycles smoothly.",
        'experience' => '15+ Years',
        'languages' => 'ID',
        'price' => '450.000',
        'rating' => '4.7',
        'sessions' => '400+',
        'original_price' => null,
        'discount' => null,
        'schedules' => ['Fri, 08:00', 'Sat, 14:00'],
        'swimlanes' => ['highly_recommended', 'evening']
    ],
    'reza' => [
        'id' => 'reza',
        'name' => 'Reza T. M. Psi., Psikolog',
        'image' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=600&h=800',
        'specialties' => ['Addiction', 'Burnout', 'Stress'],
        'badges' => 'Licensed Clinical Psychologist',
        'bio1' => "Hi, I'm Reza. My specialty lies in untangling the deep overlap between severe corporate burnout and the development of destructive coping addictions.",
        'bio2' => "Therapy with me is straightforward and actionable. We will identify the root trigger scenarios and replace behavioral dependencies with sustainable distress tolerance habits.",
        'experience' => '6+ Years',
        'languages' => 'ID, EN',
        'price' => '300.000',
        'rating' => '4.9',
        'sessions' => '110+',
        'original_price' => '350.000',
        'discount' => '-14%',
        'schedules' => ['Today, 17:00'],
        'swimlanes' => ['today']
    ],
    'dina' => [
        'id' => 'dina',
        'name' => 'Dina M. M. Psi., Psikolog',
        'image' => 'https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&q=80&w=600&h=800',
        'specialties' => ['Grief', 'Relationships'],
        'badges' => 'Licensed Clinical Psychologist',
        'bio1' => "Hello from Dina. The pain of intense grief or devastating break-ups can physically alter how we sleep, eat, and function. I am here to hold space for your profound pain without rushing you to 'get over it'.",
        'bio2' => "Through compassion-focused therapy (CFT), I will help you slowly process the loss, and find a gentle, healthy way to integrate the memory into your moving life.",
        'experience' => '8+ Years',
        'languages' => 'ID',
        'price' => '320.000',
        'rating' => '5.0',
        'sessions' => '250+',
        'original_price' => null,
        'discount' => null,
        'schedules' => ['Tomorrow, 15:00', 'Sun, 10:00'],
        'swimlanes' => ['highly_recommended']
    ]
];
